# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby CI"
on:
  push:
    branches: [ '**' ]
jobs:
  ruby-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup ImageMagick identify
        uses: AnimMouse/setup-appimage@v2
        with:
          filename: identify
          url: https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-29/ImageMagick-7.1.2-29-gcc-x86_64.AppImage
          cache_key: v1
      - run: identify -version
      - name: Setup ImageMagick magick
        uses: AnimMouse/setup-appimage@v2
        with:
          filename: magick
          url: https://github.com/ImageMagick/ImageMagick/releases/download/7.1.2-29/ImageMagick-7.1.2-29-gcc-x86_64.AppImage
          cache_key: v1
      - run: magick -version
      - name: Lint
        run: bundle exec rubocop
      - name: Test
        run: bundle exec rake test
